<?php
/**
 *
 * @var $this \Zend\View\Renderer\PhpRenderer
 */

?>
<?= $this->doctype() . PHP_EOL ?>
<html lang="ru_RU">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Test Application')->setSeparator(' - ')->setAutoEscape(false) . PHP_EOL ?>
<?php
    echo $this->headMeta() . PHP_EOL;
    echo $this->headLink() . PHP_EOL;
    echo $this->headScript() . PHP_EOL;
?></head>
<body class="bg-light">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="<?= $this->url('home') ?>">
            <img src="<?= $this->basePath('img/logo.svg') ?>" height="28" alt="TestApp"/>&nbsp;TestApp
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample07"
                aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample07">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="<?= $this->url('home') ?>">Задачи <span
                                class="sr-only">(current)</span></a>
                </li>
            </ul>
            <ul class="navbar-nav pull-right">
                <?php if ($this->identity() != null): ?>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $this->url("logout") ?>">Выход</a>
                </li>
                <?php elseif ($this->identity() == null): ?>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $this->url("login") ?>">Вход</a>
                </li>
                <?php endif; ?>
            </ul>
        </div>
    </div>
</nav>
<main role="main" class="container" id="app">
    <?= $this->content ?>
</main>
<?= $this->inlineScript() . PHP_EOL ?>
</body>
</html>
