<?php
/**
 *
 * @var $this \Zend\View\Renderer\PhpRenderer
 * @var $paginator \Zend\Paginator\Paginator
 * @var $item \Application\Entity\Issues
 */

$paginator = $this->paginator;

$sortBy = $this->sortBy;
$orderBy = $this->orderBy;

echo $this->flashMessenger()->setAutoEscape(false)->render("info", ['alert', 'alert-dismissible', 'alert-info']);
?>
<div class="card">
    <table class="table mb-0">
        <thead>
        <tr>
            <th scope="col" width="75px">
                <a href="<?= $this->url("home", [], ['query' => [
                    'sortBy' => 'id',
                    'orderBy' => ($orderBy == "ASC" ? "DESC" : "ASC")
                ]]); ?>" class="<?= $this->cId['class'] ?>">
                    <span class="text-body">ID</span>
                    <i class="<?= $this->cId['icon'] ?>"></i>
                </a>
            </th>
            <th scope="col" width="120px">
                <a href="<?= $this->url("home", [], ['query' => [
                    'sortBy' => 'status',
                    'orderBy' => ($orderBy == "ASC" ? "DESC" : "ASC")
                ]]); ?>" class="<?= $this->cStatus['class'] ?>">
                    <span class="text-body">Статус</span>
                    <i class="<?= $this->cStatus['icon'] ?>"></i>
                </a>
            </th>
            <th scope="col" width="175px">
                <a href="<?= $this->url("home", [], ['query' => [
                    'sortBy' => 'userName',
                    'orderBy' => ($orderBy == "ASC" ? "DESC" : "ASC")
                ]]); ?>" class="<?= $this->cUserName['class'] ?>">
                    <span class="text-body">Имя</span>
                    <i class="<?= $this->cUserName['icon'] ?>"></i>
                </a>
            </th>
            <th scope="col" width="175px">
                <a href="<?= $this->url("home", [], ['query' => [
                    'sortBy' => 'userEmail',
                    'orderBy' => ($orderBy == "ASC" ? "DESC" : "ASC")
                ]]); ?>" class="<?= $this->cUserEmail['class'] ?>">
                    <span class="text-body">Email</span>
                    <i class="<?= $this->cUserEmail['icon'] ?>"></i>
                </a>
            </th>
            <th scope="col" colspan="<?= $this->identity() == null ?: 2 ?>">
                <div class="d-inline float-sm-left">Задача</div>
                <div class="d-inline float-sm-right">
                    <a href="<?= $this->url("create") ?>" class="btn btn-link№ btn-outline-dark btn-secondary№ btn-sm">
                        <i class="fas fa-plus-square"></i>
                        Новая
                    </a>
                </div>
            </th>
        </tr>
        </thead>
        <tbody>
        <?php if ($paginator->count()) : ?>
            <?php foreach ($paginator as $item): ?>
                <tr>
                    <th scope="row">
                        <?php if ($item->getUpdatedAt()) : ?>
                            <span data-toggle="tooltip" data-placement="right"
                                  class="text-secondary"
                                  title="отредактировано администратором">
                                <small><sup><i class="fas fa-clipboard-check"></i></sup></small>
                            </span>
                        <?php endif; ?>
                        <?= $this->escapeHtml($item->getId()) ?>
                    </th>
                    <td>
                        <?php if ($item->isStatus()): ?>
                            <span class="badge badge-info">Завершен</span>
                        <?php else: ?>
                            <span class="badge badge-secondary">Новый</span>
                        <?php endif; ?>
                    </td>
                    <td><?= $this->escapeHtml($item->getUserName()) ?></td>
                    <td><?= $this->escapeHtml($item->getUserEmail()) ?></td>
                    <td>
                        <?= $this->escapeHtml($item->getNote()) ?>
                    </td>
                    <?php if ($this->identity()): ?>
                        <td class="text-center">
                            <a href="<?= $this->url('edit', ['id' => $item->getId()]) ?>"
                               class="btn btn-secondary btn-sm">Edit</a>
                        </td>
                    <?php endif; ?>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
            <tr>
                <td colspan="99">&nbsp;</td>
            </tr>
        <?php endif; ?>
        </tbody>
    </table>
</div>
<div class="row mt-2">
    <div class="col">
        <?= $this->paginationControl($paginator,
            'Sliding',
            'application/partial/paginator',
            ['route' => 'home', "sortBy" => $sortBy, "orderBy" => $orderBy]); ?>
    </div>
</div>



